version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: omniauth-google-oauth2
    versions:
    - 0.8.1
  - dependency-name: duktape
    versions:
    - 2.3.0.0
